spring:
  application:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DB_SERVER:localhost}:${POSTGRES_DB_PORT:5432}/ecom-db
    username: ecom
    password: Policy001
    driver: postgresql
    name: language-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

locales: en,fr # Supported locales add as you want separated by comma

