spring:
  application:
    name: language-server
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DB_SERVER:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:ecom-db}
    username: ${POSTGRES_DB_USERNAME:ecom}
    password: ${POSTGRES_DB_PASSWORD:Policy001}
    driver: postgresql
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

locales: en,fr # Supported locales add as you want separated by comma

