services:
  gateway-router:
    image: gateway-router:1.0.0
    depends_on:
      - registry-server
    environment:
      EUREKA_SERVER_URL: http://registry-server:8761/eureka
    networks:
      - ecom-network
    ports:
      - "8888:8080"
networks:
  ecom-network:
    external: true