version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=ecom
      - POSTGRES_PASSWORD=Policy001
      - POSTGRES_DB=ecom-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecom-network

volumes:
  postgres-data:

networks:
  ecom-network:
    driver: bridge
