services:
  ecom-db-server:
    image: postgres:14.15-alpine3.21
    environment:
      - POSTGRES_DB_SERVER=ecom-db-server
      - POSTGRES_DB_PORT=5432
      - POSTGRES_DB_NAME=ecom-db
      - POSTGRES_DB_PASSWORD=Policy001
      - POSTGRES_USER=ecom
      - POSTGRES_PASSWORD=Policy001
      - POSTGRES_DB=ecom-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecom-network

volumes:
  postgres-data:

networks:
  ecom-network:
    external: true
