server:
  port: 8888

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth Service Routes
        - id: authentication-server
          uri: lb://authentication-server
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /api/v1/auth/${segment}
        # Product Service Routes
        - id: product-service-routes
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RewritePath=/api/v1/products/(?<segment>.*), /api/v1/products/${segment}
        # basket Routes
        - id: basket-service-routes
          uri: lb://product-service
          predicates:
            - Path=/api/v1/baskets/**
          filters:
            - RewritePath=/api/v1/baskets/(?<segment>.*), /api/v1/baskets/${segment}
        # wishlists Service Routes
        - id: wishlists-service-routes
          uri: lb://product-service
          predicates:
            - Path=/api/v1/wishlists/**
          filters:
            - RewritePath=/api/v1/wishlists/(?<segment>.*), /api/v1/wishlists/${segment}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

