spring:
  application:
    name: db-lifecycle-server
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.yml
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_SERVER:localhost}:${POSTGRES_DB_PORT:5432}/${POSTGRES_DB_NAME:ecom-db}
    username: ${POSTGRES_DB_USERNAME:ecom}
    password: ${POSTGRES_DB_PASSWORD:Policy001}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

